version: 2

jobs:
  build:
    docker:
      image: circleci/node
    steps:
      - checkout
      - run:
          name: Build my personal docker image
          command: docker build -t mg/docker-k8s-course -f Dockerfile.dev .
      - run
          name: Run tests
          command: docker run mg/docker-k8s-course npm run test -- --coverage
